# Generated by Django 4.2.20 on 2025-06-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("QuanLyKho", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChiTietViTriCuaHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thanh_pho", models.CharField(max_length=20)),
                ("huyen", models.CharField(max_length=20)),
                ("xa", models.CharField(max_length=20)),
                ("dia_chi_chi_tiet", models.TextField()),
            ],
            options={
                "verbose_name": "Chi tiết vị trí cửa hàng",
                "verbose_name_plural": "Chi tiết vị trí cửa hàng",
                "db_table": "chi_tiet_vi_tri_cua_hang",
            },
        ),
        migrations.CreateModel(
            name="CuaHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_cua_hang", models.CharField(max_length=20, unique=True)),
                ("ten_cua_hang", models.CharField(max_length=100)),
                (
                    "so_dien_thoai",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("Hoạt_động", "Hoạt động"), ("Tạm_dừng", "Tạm dừng")],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dia_chi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TaoDon.chitietvitricuahang",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cửa hàng",
                "verbose_name_plural": "Cửa hàng",
                "db_table": "cua_hang",
            },
        ),
        migrations.CreateModel(
            name="DonXuat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_don", models.CharField(max_length=20, unique=True)),
                ("ngay_tao", models.DateField()),
                ("ngay_giao", models.DateField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Chờ_xuất", "Chờ xuất"),
                            ("Đang_xuất", "Đang xuất"),
                            ("Hoàn_thành", "Hoàn thành"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Chờ_xuất",
                        max_length=10,
                    ),
                ),
                ("qr_code_data", models.TextField(blank=True, null=True)),
                ("da_in_qr", models.BooleanField(blank=True, default=False, null=True)),
                ("nguoi_tao", models.CharField(blank=True, max_length=50, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cua_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="TaoDon.cuahang"
                    ),
                ),
            ],
            options={
                "db_table": "don_xuat",
            },
        ),
        migrations.CreateModel(
            name="ChiTietDon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong_can", models.IntegerField()),
                ("pallet_assignments", models.JSONField(blank=True, null=True)),
                (
                    "da_xuat_xong",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "don_xuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="TaoDon.donxuat"
                    ),
                ),
                (
                    "san_pham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuanLyKho.sanpham",
                    ),
                ),
            ],
            options={
                "db_table": "chi_tiet_don",
            },
        ),
    ]
