# Generated by Django 4.2.23 on 2025-06-23 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyKho', '0002_alter_chitietkiemke_pallet_and_more'),
        ('TaoDon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietdon',
            name='da_xuat_xong',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='chitietdon',
            name='don_xuat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TaoDon.donxuat'),
        ),
        migrations.AlterField(
            model_name='chitietdon',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLyKho.sanpham'),
        ),
        migrations.AlterField(
            model_name='chitietvitricuahang',
            name='huyen',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chitietvitricuahang',
            name='thanh_pho',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chitietvitricuahang',
            name='xa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cuahang',
            name='dia_chi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TaoDon.chitietvitricuahang'),
        ),
        migrations.AlterField(
            model_name='donxuat',
            name='cua_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TaoDon.cuahang'),
        ),
    ]
