# Generated by Django 4.2.20 on 2025-06-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaiDatHeThong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("khoa_cai_dat", models.CharField(max_length=100, unique=True)),
                ("gia_tri", models.TextField()),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("nhom_cai_dat", models.CharField(default="Chung", max_length=50)),
                (
                    "kieu_du_lieu",
                    models.CharField(
                        choices=[
                            ("string", "string"),
                            ("number", "number"),
                            ("boolean", "boolean"),
                            ("json", "json"),
                        ],
                        default="string",
                        max_length=7,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cai_dat_he_thong",
            },
        ),
        migrations.CreateModel(
            name="LogKiemTraGiaoHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cua_hang_dich",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cua_hang_thuc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ket_qua", models.CharField(max_length=4)),
                ("ngay_kiem_tra", models.DateTimeField(blank=True, null=True)),
                (
                    "nguoi_kiem_tra",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("vi_tri_gps", models.CharField(blank=True, max_length=100, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "log_kiem_tra_giao_hang",
            },
        ),
        migrations.CreateModel(
            name="Pallets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_pallet", models.CharField(max_length=20, unique=True)),
                ("so_thung_ban_dau", models.IntegerField()),
                ("so_thung_con_lai", models.IntegerField()),
                ("ngay_san_xuat", models.DateField()),
                ("han_su_dung", models.DateField()),
                ("ngay_kiem_tra_cl", models.DateField()),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đã_mở", "Đã mở"),
                            ("Trống", "Trống"),
                        ],
                        default="Mới",
                        max_length=5,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pallets",
            },
        ),
    ]
