# Generated by Django 4.2.20 on 2025-06-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaoTri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_bao_tri", models.CharField(max_length=20, unique=True)),
                ("tieu_de", models.CharField(max_length=200)),
                (
                    "loai_bao_tri",
                    models.CharField(
                        choices=[
                            ("Vệ_sinh", "Vệ sinh"),
                            ("Sửa_chữa", "Sửa_chữa"),
                            ("Kiểm_tra", "Kiểm tra"),
                            ("Thay_thế", "Thay thế"),
                            ("Bảo_dưỡng", "Bảo dưỡng"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "doi_tuong",
                    models.CharField(
                        choices=[
                            ("Khu_vực", "Khu vực"),
                            ("Vị_trí", "Vị trí"),
                            ("Thiết_bị", "Thiết bị"),
                            ("Hệ_thống", "Hệ thống"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "doi_tuong_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mo_ta", models.TextField()),
                (
                    "muc_do_uu_tien",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("nguoi_tao", models.CharField(max_length=50)),
                ("nguoi_thuc_hien", models.JSONField(blank=True, null=True)),
                ("thoi_gian_bat_dau", models.DateTimeField(blank=True, null=True)),
                ("thoi_gian_ket_thuc", models.DateTimeField(blank=True, null=True)),
                ("thoi_gian_uoc_tinh", models.IntegerField(blank=True, null=True)),
                (
                    "chi_phi_uoc_tinh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "chi_phi_thuc_te",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Kế_hoạch", "Kế hoạch"),
                            ("Đang_thực_hiện", "Đang_thực_hiện"),
                            ("Hoàn_thành", "Hoàn thành"),
                            ("Tạm_dừng", "Tạm dừng"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Kế_hoạch",
                        max_length=14,
                    ),
                ),
                ("ket_qua", models.TextField(blank=True, null=True)),
                ("hinh_anh_truoc", models.JSONField(blank=True, null=True)),
                ("hinh_anh_sau", models.JSONField(blank=True, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bao_tri",
            },
        ),
        migrations.CreateModel(
            name="CaiDatHeThong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("khoa_cai_dat", models.CharField(max_length=100, unique=True)),
                ("gia_tri", models.TextField()),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("nhom_cai_dat", models.CharField(default="Chung", max_length=50)),
                (
                    "kieu_du_lieu",
                    models.CharField(
                        choices=[
                            ("string", "string"),
                            ("number", "number"),
                            ("boolean", "boolean"),
                            ("json", "json"),
                        ],
                        default="string",
                        max_length=7,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cai_dat_he_thong",
            },
        ),
        migrations.CreateModel(
            name="CuaHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_cua_hang", models.CharField(max_length=20, unique=True)),
                ("ten_cua_hang", models.CharField(max_length=100)),
                ("dia_chi", models.TextField()),
                (
                    "so_dien_thoai",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("khu_vuc", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("Hoạt_động", "Hoạt động"), ("Tạm_dừng", "Tạm dừng")],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cửa hàng",
                "verbose_name_plural": "Cửa hàng",
                "db_table": "cua_hang",
            },
        ),
        migrations.CreateModel(
            name="DonXuat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_don", models.CharField(max_length=20, unique=True)),
                ("ngay_tao", models.DateField()),
                ("ngay_giao", models.DateField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Chờ_xuất", "Chờ xuất"),
                            ("Đang_xuất", "Đang xuất"),
                            ("Hoàn_thành", "Hoàn_thành"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Chờ_xuất",
                        max_length=10,
                    ),
                ),
                ("qr_code_data", models.TextField(blank=True, null=True)),
                ("da_in_qr", models.BooleanField(blank=True, default=False, null=True)),
                ("nguoi_tao", models.CharField(blank=True, max_length=50, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cua_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.cuahang",
                    ),
                ),
            ],
            options={
                "db_table": "don_xuat",
            },
        ),
        migrations.CreateModel(
            name="KhuVuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_khu_vuc", models.CharField(max_length=10, unique=True)),
                ("ten_khu_vuc", models.CharField(max_length=100)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("kich_thuoc_hang", models.IntegerField()),
                ("kich_thuoc_cot", models.IntegerField()),
                (
                    "tai_trong_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "nhiet_do_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "nhiet_do_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "do_am_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "do_am_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Hoạt_động", "Hoạt động"),
                            ("Bảo_trì", "Bảo trì"),
                            ("Ngừng", "Ngừng"),
                        ],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "khu_vuc",
            },
        ),
        migrations.CreateModel(
            name="KiemKe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_kiem_ke", models.CharField(max_length=20, unique=True)),
                ("ten_kiem_ke", models.CharField(max_length=100)),
                (
                    "loai_kiem_ke",
                    models.CharField(
                        choices=[
                            ("Toàn_kho", "Toàn kho"),
                            ("Theo_khu_vuc", "Theo khu vực"),
                            ("Theo_nhom_hang", "Theo nhóm hàng"),
                            ("Theo_han_su_dung", "Theo hạn sử dụng"),
                        ],
                        max_length=16,
                    ),
                ),
                ("pham_vi_kiem_ke", models.JSONField(blank=True, null=True)),
                ("ngay_kiem_ke", models.DateField()),
                ("nguoi_tao", models.CharField(max_length=50)),
                ("danh_sach_nguoi_kiem_ke", models.JSONField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Chuẩn_bị", "Chuẩn bị"),
                            ("Đang_kiểm_kê", "Đang kiểm kê"),
                            ("Hoàn_thành", "Hoàn thành"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Chuẩn_bị",
                        max_length=12,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "kiem_ke",
            },
        ),
        migrations.CreateModel(
            name="LogKiemTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("don_hang_id", models.CharField(max_length=20)),
                (
                    "cua_hang_dich",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cua_hang_thuc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ket_qua", models.CharField(max_length=4)),
                ("ngay_kiem_tra", models.DateTimeField(blank=True, null=True)),
                (
                    "nguoi_kiem_tra",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("vi_tri_gps", models.CharField(blank=True, max_length=100, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "log_kiem_tra",
            },
        ),
        migrations.CreateModel(
            name="NhaCungCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_nha_cung_cap", models.CharField(max_length=20, unique=True)),
                ("ten_nha_cung_cap", models.CharField(max_length=200)),
                ("dia_chi", models.TextField(blank=True, null=True)),
                (
                    "so_dien_thoai",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nguoi_lien_he",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "so_dien_thoai_lien_he",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email_lien_he",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ma_so_thue", models.CharField(blank=True, max_length=50, null=True)),
                ("loai_hang_cung_cap", models.JSONField(blank=True, null=True)),
                ("xep_hang", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Hoạt_động", "Hoạt động"),
                            ("Tạm_dừng", "Tạm dừng"),
                            ("Ngừng", "Ngừng"),
                        ],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nha_cung_cap",
            },
        ),
        migrations.CreateModel(
            name="NhomHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_nhom", models.CharField(max_length=20, unique=True)),
                ("ten_nhom", models.CharField(max_length=100)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("mau_sac", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "yeu_cau_nhiet_do_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "yeu_cau_nhiet_do_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "yeu_cau_do_am_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "yeu_cau_do_am_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tranh_anh_sang",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "tranh_rung_dong",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hang_de_vo",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hang_nguy_hiem",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("thu_tu_hien_thi", models.IntegerField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("Hoạt_động", "Hoạt động"), ("Ngừng", "Ngừng")],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "nhom_hang",
            },
        ),
        migrations.CreateModel(
            name="Pallets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_pallet", models.CharField(max_length=20, unique=True)),
                ("loai_hang", models.CharField(max_length=50)),
                ("ten_san_pham", models.CharField(max_length=100)),
                ("so_thung_ban_dau", models.IntegerField()),
                ("so_thung_con_lai", models.IntegerField()),
                ("vi_tri_kho", models.CharField(max_length=10)),
                ("ngay_san_xuat", models.DateField()),
                ("han_su_dung", models.DateField()),
                ("ngay_kiem_tra_cl", models.DateField()),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đã_mở", "Đã mở"),
                            ("Trống", "Trống"),
                        ],
                        default="Mới",
                        max_length=5,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pallets",
            },
        ),
        migrations.CreateModel(
            name="TinhTrangHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loai_tinh_trang",
                    models.CharField(
                        choices=[
                            ("Bình_thường", "Bình thường"),
                            ("Sắp_hết_hạn", "Sắp hết hạn"),
                            ("Cần_kiểm_tra_CL", "Cần kiểm tra CL"),
                            ("Có_vấn_đề", "Có vấn đề"),
                            ("Ưu_tiên_xuất", "Ưu tiên xuất"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "muc_do",
                    models.CharField(
                        choices=[
                            ("Thấp", "Thấp"),
                            ("Vừa", "Vừa"),
                            ("Cao", "Cao"),
                            ("Khẩn_cấp", "Khẩn cấp"),
                        ],
                        default="Vừa",
                        max_length=8,
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("ngay_phat_hien", models.DateField()),
                ("ngay_xu_ly", models.DateField(blank=True, null=True)),
                (
                    "nguoi_phat_hien",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nguoi_xu_ly", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đang_xử_lý", "Đang xử lý"),
                            ("Hoàn_thành", "Hoàn thành"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Mới",
                        max_length=10,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.pallets",
                    ),
                ),
            ],
            options={
                "db_table": "tinh_trang_hang",
            },
        ),
        migrations.CreateModel(
            name="ThuTuXuatHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("san_pham", models.CharField(max_length=100)),
                ("thu_tu_mac_dinh", models.IntegerField()),
                ("thu_tu_tuy_chinh", models.IntegerField(blank=True, null=True)),
                ("thoi_gian_uoc_tinh", models.IntegerField(blank=True, null=True)),
                ("khoang_cach_uoc_tinh", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "don_xuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.donxuat",
                    ),
                ),
            ],
            options={
                "db_table": "thu_tu_xuat_hang",
            },
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_san_pham", models.CharField(max_length=50, unique=True)),
                ("ten_san_pham", models.CharField(max_length=100)),
                (
                    "thuong_hieu",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dung_tich",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("don_vi_tinh", models.CharField(blank=True, max_length=20, null=True)),
                ("so_luong_per_thung", models.IntegerField(blank=True, null=True)),
                ("ma_vach", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nha_cung_cap",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("han_su_dung_mac_dinh", models.IntegerField(blank=True, null=True)),
                ("chu_ky_kiem_tra_cl", models.IntegerField(blank=True, null=True)),
                ("hinh_anh", models.CharField(blank=True, max_length=255, null=True)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("Hoạt_động", "Hoạt động"), ("Ngừng", "Ngừng")],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nhom_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.nhomhang",
                    ),
                ),
            ],
            options={
                "db_table": "san_pham",
            },
        ),
        migrations.CreateModel(
            name="LichSuXuatNhap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loai_giao_dich", models.CharField(max_length=4)),
                ("so_luong", models.IntegerField()),
                (
                    "nguoi_thuc_hien",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ngay_thuc_hien", models.DateTimeField(blank=True, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "don_xuat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.donxuat",
                    ),
                ),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.pallets",
                    ),
                ),
            ],
            options={
                "db_table": "lich_su_xuat_nhap",
            },
        ),
        migrations.CreateModel(
            name="ChiTietKiemKe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong_he_thong", models.IntegerField()),
                ("so_luong_thuc_te", models.IntegerField(blank=True, null=True)),
                ("chenh_lech", models.IntegerField(blank=True, null=True)),
                (
                    "trang_thai_hang",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nguoi_kiem_ke",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("thoi_gian_kiem_ke", models.DateTimeField(blank=True, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("hinh_anh", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kiem_ke",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.kiemke",
                    ),
                ),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.pallets",
                    ),
                ),
            ],
            options={
                "db_table": "chi_tiet_kiem_ke",
            },
        ),
        migrations.CreateModel(
            name="ChiTietDon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("san_pham", models.CharField(max_length=100)),
                ("so_luong_can", models.IntegerField()),
                ("pallet_assignments", models.JSONField(blank=True, null=True)),
                (
                    "da_xuat_xong",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "don_xuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.donxuat",
                    ),
                ),
            ],
            options={
                "db_table": "chi_tiet_don",
            },
        ),
        migrations.CreateModel(
            name="ViTriKho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_vi_tri", models.CharField(max_length=10, unique=True)),
                ("hang", models.CharField(max_length=1)),
                ("cot", models.IntegerField()),
                (
                    "loai_vi_tri",
                    models.CharField(
                        choices=[
                            ("Pallet", "Pallet"),
                            ("Carton", "Carton"),
                            ("Bulk", "Bulk"),
                        ],
                        default="Pallet",
                        max_length=6,
                    ),
                ),
                (
                    "tai_trong_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "chieu_cao_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Trống", "Trống"),
                            ("Có_hàng", "Có hàng"),
                            ("Bảo_trì", "Bảo trì"),
                            ("Hỏng", "Hỏng"),
                        ],
                        default="Trống",
                        max_length=7,
                    ),
                ),
                (
                    "uu_tien_fifo",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "gan_cua_ra",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "vi_tri_cach_ly",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "khu_vuc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.khuvuc",
                    ),
                ),
                (
                    "pallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.pallets",
                    ),
                ),
            ],
            options={
                "db_table": "vi_tri_kho",
                "unique_together": {("hang", "cot")},
            },
        ),
    ]
