# Generated by Django 5.2.3 on 2025-06-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NhapHang', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaoTri',
        ),
        migrations.RemoveField(
            model_name='chitietdon',
            name='don_xuat',
        ),
        migrations.RemoveField(
            model_name='chitietkiemke',
            name='kiem_ke',
        ),
        migrations.RemoveField(
            model_name='chitietkiemke',
            name='pallet',
        ),
        migrations.RemoveField(
            model_name='donxuat',
            name='cua_hang',
        ),
        migrations.RemoveField(
            model_name='thutuxuathang',
            name='don_xuat',
        ),
        migrations.RemoveField(
            model_name='lichsuxuatnhap',
            name='don_xuat',
        ),
        migrations.RemoveField(
            model_name='vitrikho',
            name='khu_vuc',
        ),
        migrations.RemoveField(
            model_name='lichsuxuatnhap',
            name='pallet',
        ),
        migrations.DeleteModel(
            name='NhaCungCap',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='nhom_hang',
        ),
        migrations.RemoveField(
            model_name='tinhtranghang',
            name='pallet',
        ),
        migrations.AlterUniqueTogether(
            name='vitrikho',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vitrikho',
            name='pallet',
        ),
        migrations.DeleteModel(
            name='ChiTietDon',
        ),
        migrations.DeleteModel(
            name='KiemKe',
        ),
        migrations.DeleteModel(
            name='ChiTietKiemKe',
        ),
        migrations.DeleteModel(
            name='CuaHang',
        ),
        migrations.DeleteModel(
            name='ThuTuXuatHang',
        ),
        migrations.DeleteModel(
            name='DonXuat',
        ),
        migrations.DeleteModel(
            name='KhuVuc',
        ),
        migrations.DeleteModel(
            name='LichSuXuatNhap',
        ),
        migrations.DeleteModel(
            name='NhomHang',
        ),
        migrations.DeleteModel(
            name='SanPham',
        ),
        migrations.DeleteModel(
            name='TinhTrangHang',
        ),
        migrations.DeleteModel(
            name='ViTriKho',
        ),
    ]
