# Generated by Django 4.2.20 on 2025-06-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("TaoDon", "0001_initial"),
        ("QuanLyKho", "0001_initial"),
        ("NhapHang", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pallets",
            name="nha_cung_cap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="QuanLyKho.nhacungcap",
            ),
        ),
        migrations.AddField(
            model_name="pallets",
            name="san_pham",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="QuanLyKho.sanpham"
            ),
        ),
        migrations.AddField(
            model_name="pallets",
            name="vi_tri_kho",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="QuanLyKho.vitrikho"
            ),
        ),
        migrations.AddField(
            model_name="logkiemtragiaohang",
            name="don_xuat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="TaoDon.donxuat"
            ),
        ),
    ]
