# Generated by Django 4.2.20 on 2025-07-07 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TaoDon", "0001_initial"),
        ("QuanLyKho", "0001_initial"),
        ("NhapHang", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logkiemtragiaohang",
            name="don_xuat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="TaoDon.donxuat"
            ),
        ),
        migrations.AlterField(
            model_name="pallets",
            name="ma_pallet",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="pallets",
            name="san_pham",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="QuanLyKho.sanpham"
            ),
        ),
        migrations.AlterField(
            model_name="pallets",
            name="vi_tri_kho",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="QuanLyKho.vitrikho"
            ),
        ),
    ]
