# Generated by Django 4.2.20 on 2025-06-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("NhapHang", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaoTri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_bao_tri", models.CharField(max_length=20, unique=True)),
                ("tieu_de", models.CharField(max_length=200)),
                (
                    "loai_bao_tri",
                    models.CharField(
                        choices=[
                            ("Vệ_sinh", "Vệ sinh"),
                            ("Sửa_chữa", "Sửa chữa"),
                            ("Kiểm_tra", "Kiểm tra"),
                            ("Thay_thế", "Thay thế"),
                            ("Bảo_dưỡng", "Bảo dưỡng"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "doi_tuong",
                    models.CharField(
                        choices=[
                            ("Khu_vực", "Khu vực"),
                            ("Vị_trí", "Vị trí"),
                            ("Thiết_bị", "Thiết bị"),
                            ("Hệ_thống", "Hệ thống"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "doi_tuong_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mo_ta", models.TextField()),
                (
                    "muc_do_uu_tien",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("nguoi_tao", models.CharField(max_length=50)),
                ("nguoi_thuc_hien", models.JSONField(blank=True, null=True)),
                ("thoi_gian_bat_dau", models.DateTimeField(blank=True, null=True)),
                ("thoi_gian_ket_thuc", models.DateTimeField(blank=True, null=True)),
                ("thoi_gian_uoc_tinh", models.IntegerField(blank=True, null=True)),
                (
                    "chi_phi_uoc_tinh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "chi_phi_thuc_te",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Kế_hoạch", "Kế hoạch"),
                            ("Đang_thực_hiện", "Đang_thực_hiện"),
                            ("Hoàn_thành", "Hoàn thành"),
                            ("Tạm_dừng", "Tạm dừng"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Kế_hoạch",
                        max_length=14,
                    ),
                ),
                ("ket_qua", models.TextField(blank=True, null=True)),
                ("hinh_anh_truoc", models.JSONField(blank=True, null=True)),
                ("hinh_anh_sau", models.JSONField(blank=True, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bao_tri",
            },
        ),
        migrations.CreateModel(
            name="KhuVuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_khu_vuc", models.CharField(max_length=10, unique=True)),
                ("ten_khu_vuc", models.CharField(max_length=100)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("kich_thuoc_hang", models.IntegerField()),
                ("kich_thuoc_cot", models.IntegerField()),
                (
                    "tai_trong_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "nhiet_do_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "nhiet_do_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "do_am_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "do_am_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Hoạt_động", "Hoạt động"),
                            ("Bảo_trì", "Bảo trì"),
                            ("Ngừng", "Ngừng"),
                        ],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "khu_vuc",
            },
        ),
        migrations.CreateModel(
            name="KiemKe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_kiem_ke", models.CharField(max_length=20, unique=True)),
                (
                    "loai_kiem_ke",
                    models.CharField(
                        choices=[
                            ("Toàn_kho", "Toàn kho"),
                            ("Theo_khu_vuc", "Theo khu vực"),
                            ("Theo_nhom_hang", "Theo nhóm hàng"),
                            ("Theo_han_su_dung", "Theo hạn sử dụng"),
                        ],
                        max_length=30,
                    ),
                ),
                ("pham_vi_kiem_ke", models.JSONField(blank=True, null=True)),
                ("nguoi_tao", models.CharField(max_length=50)),
                ("nguoi_phu_trach", models.JSONField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Chuẩn_bị", "Chuẩn bị"),
                            ("Đang_kiểm_kê", "Đang kiểm kê"),
                            ("Hoàn_thành", "Hoàn thành"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Chuẩn_bị",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "kiem_ke",
            },
        ),
        migrations.CreateModel(
            name="NhaCungCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_nha_cung_cap", models.CharField(max_length=20, unique=True)),
                ("ten_nha_cung_cap", models.CharField(max_length=200)),
                ("dia_chi", models.TextField(blank=True, null=True)),
                (
                    "so_dien_thoai",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nguoi_lien_he",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "so_dien_thoai_lien_he",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email_lien_he",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ma_so_thue", models.CharField(blank=True, max_length=50, null=True)),
                ("loai_hang_cung_cap", models.JSONField(blank=True, null=True)),
                ("xep_hang", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Hoạt_động", "Hoạt động"),
                            ("Tạm_dừng", "Tạm dừng"),
                            ("Ngừng", "Ngừng"),
                        ],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nha_cung_cap",
            },
        ),
        migrations.CreateModel(
            name="NhomHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_nhom", models.CharField(max_length=20, unique=True)),
                ("ten_nhom", models.CharField(max_length=100)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("mau_sac", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "yeu_cau_nhiet_do_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "yeu_cau_nhiet_do_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "yeu_cau_do_am_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "yeu_cau_do_am_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tranh_anh_sang",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "tranh_rung_dong",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hang_de_vo",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hang_nguy_hiem",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("thu_tu_hien_thi", models.IntegerField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("Hoạt_động", "Hoạt động"), ("Ngừng", "Ngừng")],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "nhom_hang",
            },
        ),
        migrations.CreateModel(
            name="ViTriKho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_vi_tri", models.CharField(max_length=10, unique=True)),
                ("hang", models.CharField(max_length=1)),
                ("cot", models.IntegerField()),
                (
                    "loai_vi_tri",
                    models.CharField(
                        choices=[
                            ("Pallet", "Pallet"),
                            ("Carton", "Carton"),
                            ("Bulk", "Bulk"),
                        ],
                        default="Pallet",
                        max_length=6,
                    ),
                ),
                (
                    "tai_trong_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "chieu_cao_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Trống", "Trống"),
                            ("Có_hàng", "Có hàng"),
                            ("Bảo_trì", "Bảo trì"),
                            ("Hỏng", "Hỏng"),
                        ],
                        default="Trống",
                        max_length=7,
                    ),
                ),
                (
                    "uu_tien_fifo",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "gan_cua_ra",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "vi_tri_cach_ly",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "khu_vuc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuanLyKho.khuvuc",
                    ),
                ),
            ],
            options={
                "db_table": "vi_tri_kho",
                "unique_together": {("hang", "cot")},
            },
        ),
        migrations.CreateModel(
            name="TinhTrangHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loai_tinh_trang",
                    models.CharField(
                        choices=[
                            ("Bình_thường", "Bình thường"),
                            ("Sắp_hết_hạn", "Sắp hết hạn"),
                            ("Cần_kiểm_tra_CL", "Cần kiểm tra CL"),
                            ("Có_vấn_đề", "Có vấn đề"),
                            ("Ưu_tiên_xuất", "Ưu tiên xuất"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "muc_do",
                    models.CharField(
                        choices=[
                            ("Thấp", "Thấp"),
                            ("Vừa", "Vừa"),
                            ("Cao", "Cao"),
                            ("Khẩn_cấp", "Khẩn cấp"),
                        ],
                        default="Vừa",
                        max_length=8,
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("ngay_phat_hien", models.DateField()),
                ("ngay_xu_ly", models.DateField(blank=True, null=True)),
                (
                    "nguoi_phat_hien",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nguoi_xu_ly", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đang_xử_lý", "Đang xử lý"),
                            ("Hoàn_thành", "Hoàn thành"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Mới",
                        max_length=10,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.pallets",
                    ),
                ),
            ],
            options={
                "db_table": "tinh_trang_hang",
            },
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_san_pham", models.CharField(max_length=50, unique=True)),
                ("ten_san_pham", models.CharField(max_length=100)),
                (
                    "thuong_hieu",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dung_tich",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("don_vi_tinh", models.CharField(blank=True, max_length=20, null=True)),
                ("so_luong_per_thung", models.IntegerField(blank=True, null=True)),
                ("ma_vach", models.CharField(blank=True, max_length=100, null=True)),
                ("han_su_dung_mac_dinh", models.IntegerField(blank=True, null=True)),
                ("chu_ky_kiem_tra_cl", models.IntegerField(blank=True, null=True)),
                ("hinh_anh", models.CharField(blank=True, max_length=255, null=True)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("Hoạt_động", "Hoạt động"), ("Ngừng", "Ngừng")],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nha_cung_cap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuanLyKho.nhacungcap",
                    ),
                ),
                (
                    "nhom_hang",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuanLyKho.nhomhang",
                    ),
                ),
            ],
            options={
                "db_table": "san_pham",
            },
        ),
        migrations.CreateModel(
            name="ChiTietKiemKe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_thung_he_thong", models.IntegerField()),
                ("han_su_dung_he_thong", models.DateField(blank=True, null=True)),
                (
                    "trang_thai_he_thong",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đã mở", "Đã mở"),
                            ("Trống", "Trống"),
                        ],
                        default="Mới",
                        max_length=10,
                    ),
                ),
                ("so_thung_thuc_te", models.IntegerField(blank=True, null=True)),
                ("han_su_dung_thuc_te", models.DateField(blank=True, null=True)),
                (
                    "trang_thai_thuc_te",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đã mở", "Đã mở"),
                            ("Trống", "Trống"),
                        ],
                        default="Mới",
                        max_length=10,
                    ),
                ),
                (
                    "tinh_trang_chat_luong",
                    models.CharField(
                        choices=[
                            ("Tốt", "Tốt"),
                            ("Khá", "Khá"),
                            ("Trung_bình", "Trung Bình"),
                            ("Kém", "Kém"),
                            ("Hỏng", "Hỏng"),
                        ],
                        default="Tốt",
                        max_length=10,
                    ),
                ),
                ("chenh_lech_so_luong", models.IntegerField(blank=True, null=True)),
                (
                    "nguoi_kiem_ke",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("thoi_gian_kiem_ke", models.DateField(blank=True, null=True)),
                ("hinh_anh", models.JSONField(blank=True, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "da_xu_ly_chenh_lech",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NhapHang.pallets",
                    ),
                ),
                (
                    "phien_kiem_ke",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuanLyKho.kiemke",
                    ),
                ),
                (
                    "san_pham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuanLyKho.sanpham",
                    ),
                ),
                (
                    "vi_tri_kho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuanLyKho.vitrikho",
                    ),
                ),
            ],
            options={
                "db_table": "chi_tiet_kiem_ke",
            },
        ),
    ]
