# Generated by Django 4.2.23 on 2025-06-23 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NhapHang', '0003_alter_logkiemtragiaohang_don_xuat_and_more'),
        ('QuanLyKho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietkiemke',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NhapHang.pallets'),
        ),
        migrations.AlterField(
            model_name='chitietkiemke',
            name='phien_kiem_ke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLyKho.kiemke'),
        ),
        migrations.AlterField(
            model_name='chitietkiemke',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLyKho.sanpham'),
        ),
        migrations.AlterField(
            model_name='chitietkiemke',
            name='tinh_trang_chat_luong',
            field=models.CharField(choices=[('Tốt', 'Tốt'), ('Khá', 'Khá'), ('Trung bình', 'Trung Bình'), ('Kém', 'Kém'), ('Hỏng', 'Hỏng')], default='Tốt', max_length=10),
        ),
        migrations.AlterField(
            model_name='chitietkiemke',
            name='vi_tri_kho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLyKho.vitrikho'),
        ),
        migrations.AlterField(
            model_name='kiemke',
            name='loai_kiem_ke',
            field=models.CharField(choices=[('Toàn bộ', 'Toàn bộ'), ('Theo khu vực', 'Theo khu vực'), ('Theo nhóm hàng', 'Theo nhóm hàng'), ('Đột xuất', 'Đột xuất'), ('Theo HSD', 'Theo hạn sử dụng')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kiemke',
            name='trang_thai',
            field=models.CharField(choices=[('Chuẩn bị', 'Chuẩn bị'), ('Đang thực hiện', 'Đang thực hiện'), ('Hoàn thành', 'Hoàn thành'), ('Tạm dừng', 'Tạm dừng'), ('Hủy', 'Hủy')], default='Chuẩn_bị', max_length=14),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='nha_cung_cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLyKho.nhacungcap'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='nhom_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLyKho.nhomhang'),
        ),
        migrations.AlterField(
            model_name='tinhtranghang',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NhapHang.pallets'),
        ),
        migrations.AlterField(
            model_name='vitrikho',
            name='khu_vuc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLyKho.khuvuc'),
        ),
    ]
