# Generated by Django 4.2.20 on 2025-07-07 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NhapHang", "0003_alter_logkiemtragiaohang_don_xuat_and_more"),
        ("QuanLyKho", "0002_alter_chitietkiemke_pallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitrikho",
            name="pallet",
            field=models.ForeignKey(
                blank=True,
                help_text="Pallet đang được lưu trữ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vi_tri_set",
                to="NhapHang.pallets",
            ),
        ),
    ]
